-- AlterTable
ALTER TABLE "public"."Order" ADD COLUMN     "cropPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "deliveryCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "gst" DOUBLE PRECISION NOT NULL DEFAULT 0;
